window.MONSTER_TTS = {
  "Are you bored?": "monster-review-assets/audio/are-you-bored-8a474248.mp3",
  "Are you cold?": "monster-review-assets/audio/are-you-cold-70b44b07.mp3",
  "Are you excited?": "monster-review-assets/audio/are-you-excited-d2de4052.mp3",
  "Are you happy?": "monster-review-assets/audio/are-you-happy-dadcb282.mp3",
  "Are you happy? Yes, I am.": "monster-review-assets/audio/are-you-happy-yes-i-am-a5148028.mp3",
  "Are you hot?": "monster-review-assets/audio/are-you-hot-828f86fd.mp3",
  "Are you hungry?": "monster-review-assets/audio/are-you-hungry-0a7f5358.mp3",
  "Are you sad?": "monster-review-assets/audio/are-you-sad-a84c5241.mp3",
  "Are you sick?": "monster-review-assets/audio/are-you-sick-17540214.mp3",
  "Are you thirsty?": "monster-review-assets/audio/are-you-thirsty-e435977e.mp3",
  "Are you tired?": "monster-review-assets/audio/are-you-tired-3775d2de.mp3",
  "He can hear music.": "monster-review-assets/audio/he-can-hear-music-adddc5fe.mp3",
  "He can see a star.": "monster-review-assets/audio/he-can-see-a-star-d066fd16.mp3",
  "He can smell a flower.": "monster-review-assets/audio/he-can-smell-a-flower-f59cb70a.mp3",
  "He can taste ice cream.": "monster-review-assets/audio/he-can-taste-ice-cream-b5b3622a.mp3",
  "He can touch a cactus.": "monster-review-assets/audio/he-can-touch-a-cactus-ad9958df.mp3",
  "He or she can hear music.": "monster-review-assets/audio/he-or-she-can-hear-music-4fe4e119.mp3",
  "He or she can see a star.": "monster-review-assets/audio/he-or-she-can-see-a-star-25197988.mp3",
  "He or she can smell a flower.": "monster-review-assets/audio/he-or-she-can-smell-a-flower-0196c060.mp3",
  "He or she can taste ice cream.": "monster-review-assets/audio/he-or-she-can-taste-ice-cream-8d683a1a.mp3",
  "He or she can touch a cactus.": "monster-review-assets/audio/he-or-she-can-touch-a-cactus-abd46231.mp3",
  "Hello! I am ready for monster review.": "monster-review-assets/audio/hello-i-am-ready-for-monster-review-d61ef95d.mp3",
  "I am bored.": "monster-review-assets/audio/i-am-bored-078ef93e.mp3",
  "I am cold.": "monster-review-assets/audio/i-am-cold-371d1f9f.mp3",
  "I am excited.": "monster-review-assets/audio/i-am-excited-87d3e21d.mp3",
  "I am happy.": "monster-review-assets/audio/i-am-happy-d9dc26f0.mp3",
  "I am hot.": "monster-review-assets/audio/i-am-hot-a41194e1.mp3",
  "I am hungry.": "monster-review-assets/audio/i-am-hungry-37ac6464.mp3",
  "I am sad.": "monster-review-assets/audio/i-am-sad-0e276ef1.mp3",
  "I am sick.": "monster-review-assets/audio/i-am-sick-c5dc3cea.mp3",
  "I am thirsty.": "monster-review-assets/audio/i-am-thirsty-4aa37259.mp3",
  "I am tired.": "monster-review-assets/audio/i-am-tired-6e8f1455.mp3",
  "I can hear music.": "monster-review-assets/audio/i-can-hear-music-9754d66a.mp3",
  "I can see a star.": "monster-review-assets/audio/i-can-see-a-star-a6f0965e.mp3",
  "I can smell a flower.": "monster-review-assets/audio/i-can-smell-a-flower-9cd45a51.mp3",
  "I can taste ice cream.": "monster-review-assets/audio/i-can-taste-ice-cream-75b42082.mp3",
  "I can touch a cactus.": "monster-review-assets/audio/i-can-touch-a-cactus-2ed70f17.mp3",
  "Is he bored?": "monster-review-assets/audio/is-he-bored-7b3a7e74.mp3",
  "Is he cold?": "monster-review-assets/audio/is-he-cold-9ff71769.mp3",
  "Is he excited?": "monster-review-assets/audio/is-he-excited-3912f45d.mp3",
  "Is he happy?": "monster-review-assets/audio/is-he-happy-4fcc012f.mp3",
  "Is he hot?": "monster-review-assets/audio/is-he-hot-ed04a9e7.mp3",
  "Is he hungry?": "monster-review-assets/audio/is-he-hungry-7c26d53f.mp3",
  "Is he sad?": "monster-review-assets/audio/is-he-sad-9489e7f9.mp3",
  "Is he sick?": "monster-review-assets/audio/is-he-sick-944cfb01.mp3",
  "Is he thirsty?": "monster-review-assets/audio/is-he-thirsty-18dda6d0.mp3",
  "Is he tired?": "monster-review-assets/audio/is-he-tired-f44bd911.mp3",
  "Is she bored?": "monster-review-assets/audio/is-she-bored-a6883147.mp3",
  "Is she cold?": "monster-review-assets/audio/is-she-cold-aac3565a.mp3",
  "Is she excited?": "monster-review-assets/audio/is-she-excited-090c958a.mp3",
  "Is she happy?": "monster-review-assets/audio/is-she-happy-91105198.mp3",
  "Is she hot?": "monster-review-assets/audio/is-she-hot-41573de9.mp3",
  "Is she hungry?": "monster-review-assets/audio/is-she-hungry-62fe9cc7.mp3",
  "Is she sad?": "monster-review-assets/audio/is-she-sad-3b31e5f6.mp3",
  "Is she sick?": "monster-review-assets/audio/is-she-sick-7ee540be.mp3",
  "Is she thirsty?": "monster-review-assets/audio/is-she-thirsty-3c09e5b2.mp3",
  "Is she tired?": "monster-review-assets/audio/is-she-tired-142bea4c.mp3",
  "My finger hurts.": "monster-review-assets/audio/my-finger-hurts-fde623be.mp3",
  "My hand hurts.": "monster-review-assets/audio/my-hand-hurts-08738923.mp3",
  "My leg hurts.": "monster-review-assets/audio/my-leg-hurts-2d518c86.mp3",
  "No, I'm not.": "monster-review-assets/audio/no-i-m-not-b47da5c1.mp3",
  "No, he isn't.": "monster-review-assets/audio/no-he-isn-t-3acbb09a.mp3",
  "No, she isn't.": "monster-review-assets/audio/no-she-isn-t-52b2bf6c.mp3",
  "She can hear music.": "monster-review-assets/audio/she-can-hear-music-963de135.mp3",
  "She can see a star.": "monster-review-assets/audio/she-can-see-a-star-4a865f7f.mp3",
  "She can smell a flower.": "monster-review-assets/audio/she-can-smell-a-flower-d1c3151c.mp3",
  "She can taste ice cream.": "monster-review-assets/audio/she-can-taste-ice-cream-40032af8.mp3",
  "She can touch a cactus.": "monster-review-assets/audio/she-can-touch-a-cactus-bdbbad56.mp3",
  "This is my finger.": "monster-review-assets/audio/this-is-my-finger-db17a359.mp3",
  "This is my hand.": "monster-review-assets/audio/this-is-my-hand-6d86823a.mp3",
  "This is my leg.": "monster-review-assets/audio/this-is-my-leg-376d4f0e.mp3",
  "What's wrong?": "monster-review-assets/audio/what-s-wrong-48dabfbb.mp3",
  "Yes, I am.": "monster-review-assets/audio/yes-i-am-76ab27eb.mp3",
  "Yes, he is.": "monster-review-assets/audio/yes-he-is-165119ab.mp3",
  "Yes, she is.": "monster-review-assets/audio/yes-she-is-964b6939.mp3"
};
